# Generated by Django 4.2.8 on 2023-12-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_chosen_flavour_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='chosen_flavour',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
