# Generated by Django 4.2.8 on 2023-12-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_cart_product_cartitem_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='chosen_product',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
