# Generated by Django 4.2.8 on 2023-12-29 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_cartitem_chosen_product_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='chosen_product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='chosen_flavour',
            field=models.CharField(default='no flavour', max_length=100),
        ),
    ]
